title: Your Name  # your name (or website title) here
<img width="150" height="150" src= "/images/fing.jpg?raw=true"> # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br>
  Hi there! My name is Fifing, don't ask me why. I'm a technology enthusiast.
  <br>
  Email: fifing@solu.co.id
  <p class="view"><a href="https://fifing3.github.io/">Education</a> | <a href="https://fifing3.github.io/experience">Experience</a> | <a href="https://fifing3.github.io/research">Research</a> | <a href="https://fifing3.github.io/presentation">Presentation</a> | <a href="https://fifing3.github.io/certificates">Certificates</a> | <a href="https://fifing3.github.io/projects">Projects</a></p>
  <br>
  <br>

theme: jekyll-theme-minimal
# remote_theme: opengitdocs/jekyll
google_analytics: G-Q3Y4PHSLM9 # your Google Analytics tracking ID here
